apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-app-deployment
  labels:
    app: your-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault  # Set the seccomp profile to runtime/default
      containers:
      - name: your-app-container
        image: your-app-image:latest
        securityContext:
          capabilities:
            drop:
            - NET_RAW  # Drop the NET_RAW capability
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          limits:
            memory: "1Gi"
          requests:
            memory: "512Mi"
