name: Java CICD with Gradle
 
on:
  push:
    branches: ["main"]

permissions:
  contents: read

env:
  DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }}

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Grant permission for gradle
        run: chmod +x gradlew

      - name: Execute Gradle build
        run: ./gradlew build

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Install Datree
        run: curl https://get.datree.io | /bin/bash
        
      - name: Run Datree's policy check
        run: datree test kube.yaml
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
             alanpramil7/javaapp:${{ github.run_number }}
             alanpramil7/javaapp:latest
             
      - name: Delete docker images 
        run: |
            docker rmi alanpramil7/javaapp:${{ github.run_number }} alanpramil7/javaapp:latest
      
